apiVersion: v1
kind: Service
metadata:
  name: webscanner-backend-service
  labels:
    app: webscanner-backend
spec:
  selector:
    app: webscanner-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP