apiVersion: v1
kind: Service
metadata:
  name: webscanner-frontend-service
  labels:
    app: webscanner-frontend
spec:
  selector:
    app: webscanner-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP